"""Rendering of the impact brief.

Two consumers, one source of truth: the Markdown goes to the terminal and the
pull request, and the same content is what gets written back into DataHub as a
document, so the graph and the human read the identical brief.
"""

from __future__ import annotations

from .models import BlastReport, RiskAssessment, Severity

SEVERITY_LABEL = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH: "HIGH",
    Severity.MODERATE: "MODERATE",
    Severity.LOW: "LOW",
}


def render_markdown(report: BlastReport, limit: int = 15) -> str:
    """Render the full brief.

    Assembled from sections rather than one long append run, because the two
    ownership sections are the same shape and were written out twice. One
    builder means a wording fix cannot land on "nobody owns this" and miss "we
    did not check", which are the two the brief works hardest to keep apart.
    """
    return "\n".join(
        [
            *_header(report),
            *_ranked_section(report, limit),
            *_asset_list_section(
                "## Impacted with no owner to notify",
                f"{len(report.unowned)} impacted asset(s) have nobody to notify",
                report.unowned,
                limit,
            ),
            # Kept separate from the list above on purpose. "We did not look" is
            # a different finding from "there is nobody", and merging them sends
            # someone hunting for a governance gap that may not exist.
            *_asset_list_section(
                "## Ownership not checked",
                f"{len(report.unchecked_ownership)} impacted asset(s) could not be "
                "enriched, so their ownership is unknown rather than absent",
                report.unchecked_ownership,
                limit,
            ),
            *_notify_section(report),
            "---",
            "Generated by [Blast Radar](https://github.com/voyagi/datahub-blast-radar). "
            "Scores are deterministic: same graph in, same ranking out.",
        ]
    )


def _header(report: BlastReport) -> list[str]:
    return [
        f"# Blast radius: {_cell(report.root.name)}",
        "",
        # Escaped like the rest, even though this one is typed by whoever ran
        # the scan rather than read out of the catalog. It lands in the same
        # published document, and "the caller would not attack themselves"
        # stops being true the moment a CI job passes a branch name through.
        f"**Change:** {_cell(report.change_summary)}",
        # No code span around the URN. Backslash escapes do not apply inside
        # one, so a code span is the only place `_cell` cannot protect, and a
        # backtick in the string would end it and let the rest render as
        # Markdown. Plain text, escaped, matches the ranked table anyway.
        f"**Asset:** {_cell(report.root.urn)}",
        f"**Scanned:** {len(report.assessments)} downstream assets "
        f"across {report.hops_traversed} hops "
        f"at {report.generated_at:%Y-%m-%d %H:%M UTC}",
        *(f"**Note:** {note}" for note in disclosure_notes(report)),
        "",
        _verdict(report),
        "",
    ]


def _ranked_section(report: BlastReport, limit: int) -> list[str]:
    ranked = report.ranked[:limit]
    if not ranked:
        return []

    lines = ["## Ranked impact", ""]
    if len(report.ranked) > limit:
        lines += [f"The {limit} highest-scoring of {len(report.ranked)} consumers.", ""]
    lines += [
        "| # | Asset | Type | Score | Severity | Why |",
        "|---|---|---|---:|---|---|",
    ]
    lines += [
        f"| {index} | {_cell(item.node.entity.name)} | "
        f"{_cell(item.node.entity.display_type)} | {item.score} | "
        f"{SEVERITY_LABEL[item.severity]} | {_cell(_why(item))} |"
        for index, item in enumerate(ranked, start=1)
    ]
    return [*lines, ""]


def _cell(text: str) -> str:
    """Escape the Markdown a catalog string could otherwise become.

    Every string in this brief came out of the catalog, and the brief is
    published back into DataHub for other people to read before they ship a
    change. So the question for each character is not whether it renders
    oddly, it is whether it changes what the document says:

    * a pipe closes a table cell and opens another, so `orders | 99 | LOW`
      renders as a row with a score and a severity nobody computed;
    * a backtick closes the code span the asset lists wrap names in, which
      lets everything after it render as Markdown rather than as a name;
    * a bracket opens a link, and a fabricated link in a document published
      onto an asset page is phishing with the catalog's own credibility;
    * a less-than sign opens a tag wherever the reader's renderer allows raw
      HTML, and this brief is read in at least two of them;
    * a backslash decides whether any of the above is escaped at all, so it
      goes first. `orders \\| 99` would otherwise leave an escaped backslash
      followed by a live pipe.

    Asterisks, underscores and tildes are deliberately left alone. They can
    only make text bold, italic or struck through, and escaping them would put
    a backslash into every `shop.orders_v2` in a file people also read raw. A
    bare URL in a name is left alone for a different reason: renderers that
    autolink one show the target as the link text, so it can be ugly but it
    cannot claim to lead somewhere it does not.
    """
    escaped = text.replace("\\", "\\\\")
    for character in "`|[]<":
        escaped = escaped.replace(character, f"\\{character}")
    return escaped


def _asset_list_section(
    title: str, intro: str, items: list[RiskAssessment], limit: int
) -> list[str]:
    """One bulleted list of assets, or nothing at all when there are none."""
    if not items:
        return []
    return [
        title,
        "",
        f"{intro}{_list_intro_tail(len(items), limit)}",
        "",
        *(f"- {_cell(item.node.entity.name)} (score {item.score})" for item in items[:limit]),
        "",
    ]


def _notify_section(report: BlastReport) -> list[str]:
    notify = _notify_list(report)
    if not notify:
        return []

    lines = ["## Who to tell", ""]
    for name, assets in sorted(notify.items()):
        joined = ", ".join(_cell(asset) for asset in sorted(assets)[:6])
        more = f" (+{len(assets) - 6} more)" if len(assets) > 6 else ""
        lines.append(f"- **{_cell(name)}** - {joined}{more}")
    return [*lines, ""]


def render_summary(report: BlastReport) -> str:
    """One-line summary, used for tags and terminal output."""
    critical = len(report.by_severity(Severity.CRITICAL))
    high = len(report.by_severity(Severity.HIGH))
    return (
        f"{len(report.assessments)} downstream assets, "
        f"{critical} critical, {high} high, "
        f"{len(report.unowned)} without an owner"
    )


def disclosure_notes(report: BlastReport) -> list[str]:
    """Every reason this scan saw less than the whole cone, in plain sentences.

    Both renderers read this list. While the wording lived inside
    `render_markdown`, the terminal disclosed neither truncation nor a capped
    lineage reply, so the README's headline command - the one without `--out` -
    printed a table that read complete when it was a sample. One list, two
    consumers, and no second copy of the rule to drift.

    The sentences avoid "above" and "below": the same text sits under a header
    in the brief and under the ranked table in the terminal.
    """
    notes: list[str] = []
    if report.truncated:
        notes.append(
            "Traversal hit its node budget, so the cone reported here is a "
            "subset, and which consumers survived is arbitrary with respect "
            "to distance. Raise `BLAST_RADAR_MAX_NODES` for the full picture."
        )
    if report.capped_lineage:
        notes.append(
            f"{len(report.capped_lineage)} asset(s) returned fewer consumers "
            f"than DataHub holds. {_shortfall(report)}. Raise "
            "`BLAST_RADAR_RESULTS_PER_HOP` and re-run."
        )
    return notes


def _list_intro_tail(total: int, limit: int) -> str:
    """End a list's intro sentence, naming the cut when `limit` makes one.

    A list that stops at `limit` with no note is the same lie as a truncated
    cone with no note: it reads complete because nothing said otherwise.
    """
    if total > limit:
        return f", the {limit} highest-scoring of them:"
    return ":"


def _shortfall(report: BlastReport) -> str:
    """The capped note's middle sentence: how much is missing, honestly.

    Three cases, and only one of them is a number. An asset whose reply
    carried no usable total contributes no count at all, so a scan where none
    of them carried one has an unknown shortfall - never a zero, which would
    read as "nothing is missing" on the line that exists to say something is.

    "No usable total" covers both shapes the adapter refuses to count: a reply
    with no total, and one whose total does not exceed what it returned. The
    wording says "usable" rather than "missing" for that reason.
    """
    missing = report.consumers_missing
    uncounted = report.capped_without_a_count
    if missing is None:
        return "How many are missing is unknown: not one of them came back with a usable total"
    detail = f"{missing} consumer(s) are missing from this scan"
    if uncounted:
        detail += (
            f", plus an unstated number from {uncounted} asset(s) whose reply "
            "carried no usable total"
        )
    return detail


def _verdict(report: BlastReport) -> str:
    if not report.assessments:
        # No guard for "truncated but empty" here: the walk refuses a budget
        # below one rather than returning an unwalked cone, and truncation
        # otherwise means the budget was spent, which takes at least one node.
        # A branch that cannot be true reads as coverage and provides none.
        return "**Verdict:** nothing downstream depends on this asset. Safe to change."
    if report.headline_count == 0:
        return (
            "**Verdict:** downstream consumers exist but none scored above "
            "moderate. Normal review applies."
        )
    return (
        f"**Verdict:** {report.headline_count} high-or-critical consumers. "
        "Notify the owners below before this ships."
    )


def _why(item: RiskAssessment) -> str:
    top = item.top_factors[:2]
    return "; ".join(factor.evidence for factor in top) or "no contributing signal"


def _notify_list(report: BlastReport) -> dict[str, set[str]]:
    """Map each owner to the impacted assets they own.

    Built from the high-and-above band only. A notify list that includes every
    low-severity consumer is one nobody reads.
    """
    notify: dict[str, set[str]] = {}
    for item in report.ranked:
        if item.severity.rank < Severity.HIGH.rank:
            continue
        for owner in item.notify():
            notify.setdefault(owner.name, set()).add(item.node.entity.name)
    return notify
